AllCops:
  NewCops: enable
  Exclude:
    - 'judopay.gemspec'
    - 'spec/factories.rb'
    - 'vendor/cache/**/*'

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Max: 65

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 141

Metrics/MethodLength:
  Max: 80

Metrics/ParameterLists:
  MaxOptionalParameters: 4

Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/SymbolArray:
  Enabled: false
